"""Done done

Revision ID: fa7d53868ca1
Revises: 7feb640521df
Create Date: 2025-05-19 16:42:47.769968

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "fa7d53868ca1"
down_revision: Union[str, None] = "7feb640521df"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("labs_user_id_fkey", "labs", type_="foreignkey")
    op.drop_column("labs", "user_id")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "labs", sa.Column("user_id", sa.INTEGER(), autoincrement=False, nullable=False)
    )
    op.create_foreign_key("labs_user_id_fkey", "labs", "users", ["user_id"], ["id"])
    # ### end Alembic commands ###
